name: kala_connect
description: A tactile, voice-first marketplace for traditional Indian artisans.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cloud_firestore: ^6.9.0
  firebase_auth: ^6.6.1
  firebase_core: ^4.14.0
  firebase_storage: ^13.5.0
  flutter:
    sdk: flutter
  flutter_tts: ^4.2.5
  google_mlkit_image_labeling: ^0.15.0
  google_sign_in: ^7.2.0
  image: ^4.9.2
  image_picker: ^1.2.3
  provider: ^6.1.2
  shared_preferences: ^2.5.5
  speech_to_text: ^7.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
